services:
  postgres:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: piksel_user
      POSTGRES_DB: piksel_db
      POSTGRES_PASSWORD: passwordPiksel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  odc:
    build:
      context: ../
      dockerfile: docker/odc/Dockerfile
    environment:
      - ODC_DEFAULT_DB_USERNAME=piksel_user
      - ODC_DEFAULT_DB_DATABASE=piksel_db
      - ODC_DEFAULT_DB_HOSTNAME=postgres
      - ODC_DEFAULT_DB_PASSWORD=passwordPiksel
    volumes:
      - ../datacube.conf:/root/.datacube.conf
      - ../products:/home/venv/products
    depends_on:
      - postgres
    restart: always

  jupyter:
    build:
      context: ../
      dockerfile: docker/jupyter/Dockerfile
    user: "1000:1000"
    environment:
      - ODC_DEFAULT_DB_USERNAME=piksel_user
      - ODC_DEFAULT_DB_DATABASE=piksel_db
      - ODC_DEFAULT_DB_HOSTNAME=postgres
      - ODC_DEFAULT_DB_PASSWORD=passwordPiksel
      - PYTHONPATH=/home/venv/notebooks
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/venv/notebooks
      - ../datacube.conf:/home/jupyter/.datacube.conf
    depends_on:
      - postgres
      - odc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  postgres_data:
