services:
  postgres:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: piksel_user
      POSTGRES_DB: piksel_db
      POSTGRES_PASSWORD: passwordPiksel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  odc:
    build: .
    ports:
      - "8888:8888"
    environment:
      - DB_HOSTNAME=postgres
      - ODC_DEFAULT_DB_HOSTNAME=postgres
      - DB_USERNAME=piksel_user
      - ODC_DEFAULT_DB_USERNAME=piksel_user
      - DB_DATABASE=piksel_db
      - ODC_DEFAULT_DB_DATABASE=piksel_db
      - DB_PASSWORD=passwordPiksel
      - ODC_DEFAULT_DB_PASSWORD=passwordPiksel
    volumes:
      - ../datacube.conf:/root/.datacube.conf
      - ../notebooks:/home/venv/notebooks
      - ../products:/home/venv/products
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
