services:
  postgres:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - piksel-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  odc:
    build:
      context: ../
      dockerfile: docker/odc/Dockerfile
    environment:
      - ODC_DEFAULT_DB_USERNAME=${POSTGRES_USER}
      - ODC_DEFAULT_DB_DATABASE=${POSTGRES_DB}
      - ODC_DEFAULT_DB_HOSTNAME=${POSTGRES_HOST}
      - ODC_DEFAULT_DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - piksel-net
    volumes:
      - ../datacube.conf:/root/.datacube.conf
      - ../products:/home/venv/products
    depends_on:
      - postgres
    restart: always
    command: tail -f /dev/null
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - |
          python -c 'import datacube; import os;
          try: 
              dc = datacube.Datacube();
              dc.index.datasets.get_field_names();
              print("Datacube fully operational");
              exit(0)
          except Exception as e:
              print("Basic health check passed but database may not be initialized");
              exit(0)'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  jupyter:
    build:
      context: ../
      dockerfile: docker/jupyter/Dockerfile
    user: "1000:1000"
    environment:
      - ODC_DEFAULT_DB_USERNAME=${POSTGRES_USER}
      - ODC_DEFAULT_DB_DATABASE=${POSTGRES_DB}
      - ODC_DEFAULT_DB_HOSTNAME=${POSTGRES_HOST}
      - ODC_DEFAULT_DB_PASSWORD=${POSTGRES_PASSWORD}
      - PYTHONPATH=/home/venv/notebooks
      - JUPYTER_ENABLE_LAB=yes
      - ODC_CONFIG_PATH=${ODC_CONFIG_PATH}
    ports:
      - "${JUPYTER_PORT}:8888"
    networks:
      - piksel-net
    volumes:
      - ../notebooks:/home/venv/notebooks
      - ../datacube.conf:/home/venv/datacube.conf
    depends_on:
      - postgres
      - odc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  piksel-net:
    name: piksel-net

volumes:
  postgres_data:
